### ISSUE TITLE
Not Working with our Private Repo

### ISSUE THREAD

**Issue by maverick3609** [FundersClub/fire#100]
HI

I have tried this, added fire-bot as a collaborator to our private repo. But I am still getting awaiting fire-bots response. Though I can login on your website and it shows the repository that I wanted to link. Something is missing somewhere that it is not working of me.

**Comment by eranrund** [comment]
Hello,

Would you mind sharing the repository organization/name?
If you prefer not to share it publicly over here, please e-mail me directly at eran@fundersclub.com

Thanks!

**Comment by eranrund** [comment]
This has been resolved.
