### ISSUE TITLE
Giant Empty 'Choose a Repository' screen

### ISSUE THREAD

**Issue by rainwoodman** [FundersClub/fire#190]
On Firefox.

After login, I see an empty Choose a Repository screen -- no repos are listed.

![screenshot from 2017-09-18 13-32-55](https://user-images.githubusercontent.com/138060/30563181-e9ce1e38-9c75-11e7-93b7-43c9aa12e5a0.png)

**Comment by eranrund** [comment]
Is that still a problem? It looks like you managed to configure some users.

**Comment by rainwoodman** [comment]
Thanks.

- I followed the link in the fire-bot issue to configure users.
- Now I see the repo in the list. Is there a delay or do I must follow the link in the fire-bot issue first before it shows up in the 'Choose a Repository' page?

**Comment by eranrund** [comment]
You must follow the link.

**Comment by Andreas-Schoenefeldt** [comment]
Hi guys, also ran into this issue, and it is actually super hard, to make the jump from the empty page to get it going. 

If no repository is added, would it be possibel to add just a hint like this:

> please give our github user **fire-bot** read access to the repositories you would like to connect with fire.

**Comment by eranrund** [comment]
Thanks for the feedback and compliment! This makes sense, I'll take care of it when I get a chance.
