### ISSUE TITLE
Email Layout is not ideal

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [FundersClub/fire#197]
hi Guys, first of all thank you for this amazing service!

If I had a wish, I would like to see the issue head of forewarded emails more precise. The current Look:

<img width="625" alt="screen shot 2017-10-06 at 12 51 09" src="https://user-images.githubusercontent.com/1157580/31274848-0f357f90-aa95-11e7-963a-dc19c4f5feb3.png">

I see two issues:
1. the bold does not work, because there is a space on the wrong side of the closing **
1. there is to much space between the lines

Ideally it could look like this?

>**From:** Schule für Viszerale Therapie <info@viszerale-therapie.at>   
>**Subject:** Titel in Nameskarte falsch und nicht veränderbar   
>**Date:** 5 October 2017 at 16:02:23 GMT+2   
> **To:** Andreas Schönefeldt <technik@viszerale-therapie.at>   

The email was forewarded with Mac Mail (El Captain)

**Comment by eranrund** [comment]
Good feedback, thank you! I'll try looking into it when I can.
