### ISSUE TITLE
Custom email domain to send emails to

### ISSUE THREAD

**Issue by bharadwajth** [FundersClub/fire#270]
When setting up the fire-bot, I am presented with an email address to send emails to, to create issues.
I've attached a screenshot to clarify. 

Right now, it says <random>@fire.fundersclub.com. Can I change it to <random>@<my_own_domain.com>?

![fire](https://user-images.githubusercontent.com/8296827/39829394-86f8d542-537b-11e8-9cf5-503a9f77eee7.jpg)

**Comment by eranrund** [comment]
If you want to use a custom email domain you need to host it yourself and configure email forwarding from @your-domain to @fire.fundersclub.com

**Comment by eranrund** [comment]
Actually, thinking about it more, I am not sure the bot will properly recognize the message when forwarding is used. We'll need to look into it.

**Comment by cruisinggoddess** [comment]
+1 for this feature

**Comment by eranrund** [comment]
Setting forwarding should work.
