### ISSUE TITLE
How do I remove the email address in tickets created?

### ISSUE THREAD

**Issue by oseyx** [FundersClub/fire#330]
Currently when I send a ticket to my `xyz@fire.fundersclub.com` email address, the ticket is created on my repository *with* my email address in plain view...

How do I go about disabling the adding of the email to the ticket that is created?

Ideally, our business doesn't want the internal email addresses being used visible to the public. And re-editing the tickets is time consuming and doesn't remove them from the issue (on GitHub)'s history.

**Comment by eranrund** [comment]
I added an option to allow disabling including the sender's email address in the issue:
![image](https://user-images.githubusercontent.com/1485066/46768557-6e76a080-cc9d-11e8-9232-fd3b3cf5a16b.png)

Enjoy!
