### ISSUE TITLE
Demonstrate your product in action by advertising an email address to submit issues to this repo

### ISSUE THREAD

**Issue by ebblake** [FundersClub/fire#350]
*The questions below are a good starting place for creating your issue*

* Is this a bug, feature request, usability issue, engineering change, or something else?

Bug - https://github.com/FundersClub/fire/blob/master/CONTRIBUTING.md does not list an email address, and yet the whole point of the bot is so that users can submit issues by emailing rather than logging into github

* Have any ideas on how to fix/resolve/improve the issue?

Update your contribution page to mention the email address to use to test out what happens when you submit an issue to this project via email.

**Comment by eranrund** [comment]
Good idea. I created a test repo (https://github.com/FundersClub/fire-test/issues) and a test email (fire-test@fire.fundersclub.com ) and mentioned it in our README.
Thanks for the suggestion!
