### ISSUE TITLE
Issues don't get created

### ISSUE THREAD

**Issue by ThexXTURBOXx** [FundersClub/fire#359]
I tried to set fire up for my repo https://github.com/ThexXTURBOXx/studip-app-uni-passau/issues.
Right now, I tried sending 2 mails to the firebot-email (studipapp@fire.fundersclub.com), but they still (after half an hour) aren't shown in the issues page.
Is the bot broken right now?

**Comment by eranrund** [comment]
I just emailed the bot (`studipapp@fire.fundersclub.com`) and it worked - https://github.com/ThexXTURBOXx/studip-app-uni-passau/issues/9
Did your email bounce?

**Comment by ThexXTURBOXx** [comment]
Very weird... Tested it yesterday, sent 5 Emails, all of them went through. Tested it right now - works just fine. Then, I think, this is solved... Thank you ^^
