### ISSUE TITLE
Fire continues using my old GitHub username

### ISSUE THREAD

**Issue by blakegearin** [FundersClub/fire#423]
*The questions below are a good starting place for creating your issue*

* Is this a bug, feature request, usability issue, engineering change, or something else?
  * Bug where Fire is using/associated my old GitHub username and won't let me do anything with my new one. I can access an old repo but not new ones

* What steps reliably reproduce the issue?
    1. Go to https://fire.fundersclub.com/
    2. Click Login
    3. Enter credentials
    4. Logged in with wrong username at the top
* Have any ideas on how to fix/resolve/improve the issue?
  * Manual change in your database...?
* If relevant, can you provide a screenshot/video/gif highlighting the change?
  * Tried in Chrome and Firefox, same results
   * Logging in:
![logging in](https://user-images.githubusercontent.com/17950836/87121510-81d6e700-c248-11ea-886d-144f044912d3.jpg)

    * Logged in:
![logged in](https://user-images.githubusercontent.com/17950836/87121504-800d2380-c248-11ea-883b-f04bdf2860ae.jpg)

**Comment by eranrund** [comment]
Hey @blakegearin 
Can you send an email from the email address that was associated with @blakebuthod to eran@fundersclub.com?
I can change the database but I need a way to figure out you are indeed @blakebuthod. Hope this is okay. Thanks!
